### ISSUE TITLE
mermaid 버전업 부탁드립니다

### ISSUE THREAD

**Issue by Yangeok** [heycalmdown/notion-mermaid#5]
[8.9.0](https://unpkg.com/browse/mermaid@8.9.0/)버전까지 나왔는데 아직 8.4.4로 되어있어서 이슈 남기고 갑니다!

**Comment by heycalmdown** [comment]
올려놨습니다. 혹시 직접 배포해서 쓰시나요, 아니면 제가 올려놓은 mermaid.kson.live 사용하시나요? 후자라면 제가 Apex up 토큰을 까먹어서 그쪽은 내일쯤에나 올라갈거 같습니다.

**Comment by Yangeok** [comment]
피드백 주셔서 감사합니다! 직접 버전업시켜서 배포해가지고 쓰고 있습니다 :) 

새해복 많이 받으세요 ㅎㅎ
